language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - cargo run --example artists_albums
  - cargo run --example track
  - cargo run --example artist_related_artists
  - cargo run --example tracks
  - cargo run --example artist_top_tracks
  - cargo run --example user
  - cargo run --example artists
  - cargo run --example albums
  - cargo run --example audios_features
  - cargo run --example audio_analysis
  - cargo run --example album_tracks
  - cargo run --example audio_features
  - cargo run --example artist
  - cargo run --example album
