[package]
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
name = "rspotify"
version = "0.10.0"
license = "MIT"
readme = "README.md"
description="Spotify API wrapper"
homepage="https://github.com/samrayleung/rspotify"
repository="https://github.com/samrayleung/rspotify"
keywords=["spotify","api"]
edition = "2018"
[dependencies]
base64 = "0.10.0"
derive_builder = "0.7"
dotenv = "0.13.0"
env_logger = "0.6.0"
itertools = "0.8.0"
log = "0.4"
percent-encoding = "1.0.1"
rand = "0.6.5"
random = "0.12.2"
reqwest-default-tls ={ version = "0.10", features=["json","socks"], optional = true, package = "reqwest" }
reqwest-native-tls ={ version = "0.10", features=["json","socks", "native-tls"], default-features = false, optional = true,  package = "reqwest"}
reqwest-native-tls-vendored ={ version = "0.10", features=["json","socks", "native-tls-vendored"], default-features = false, optional = true, package = "reqwest" }
reqwest-rustls-tls ={ version = "0.10", features=["json","socks", "rustls-tls"], default-features = false, optional = true, package = "reqwest" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
webbrowser = "0.5.0"
lazy_static = "1.0"
failure = "0.1"
secret_structs = {path = "../../../ifc_library/secret_structs"}
secret_macros = {path = "../../../ifc_library/macros"}

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"

[features]
default = ["default-tls"]
default-tls = ["reqwest-default-tls"]
blocking = ["reqwest-default-tls/blocking"]
# Enables native-tls specific functionality not available by default.
native-tls = ["reqwest-native-tls"]
native-tls-blocking = ["reqwest-native-tls/blocking"]
native-tls-vendored = ["reqwest-native-tls-vendored"]
native-tls-vendored-blocking = ["reqwest-native-tls-vendored/blocking"]
rustls-tls = ["reqwest-rustls-tls"]
rustls-tls-blocking = ["reqwest-rustls-tls/blocking"]

[[example]]
name = "device"
required-features = ["blocking"]
path = "examples/blocking/device.rs"

[[example]]
name = "artist_top_tracks"
required-features = ["blocking"]
path = "examples/blocking/artist_top_tracks.rs"

[[example]]
name = "categories"
required-features = ["blocking"]
path = "examples/blocking/categories.rs"

[[example]]
name = "blocking_current_playback"
required-features = ["blocking"]
path = "examples/blocking/current_playback.rs"
            

[[example]]
name = "blocking_current_playing"
required-features = ["blocking"]
path = "examples/blocking/current_playing.rs"
            

[[example]]
name = "current_user_followed_artists"
required-features = ["blocking"]
path = "examples/blocking/current_user_followed_artists.rs"
            

[[example]]
name = "current_user_playing_track"
required-features = ["blocking"]
path = "examples/blocking/current_user_playing_track.rs"
            

[[example]]
name = "current_user_playlists"
required-features = ["blocking"]
path = "examples/blocking/current_user_playlists.rs"
            

[[example]]
name = "current_user_recently_played"
required-features = ["blocking"]
path = "examples/blocking/current_user_recently_played.rs"
            

[[example]]
name = "current_user_saved_albums_add"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_albums_add.rs"
            

[[example]]
name = "current_user_saved_albums_contains"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_albums_contains.rs"
            

[[example]]
name = "current_user_saved_albums_delete"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_albums_delete.rs"
            

[[example]]
name = "current_user_saved_albums"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_albums.rs"
            

[[example]]
name = "current_user_saved_tracks_add"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_tracks_add.rs"
            

[[example]]
name = "current_user_saved_tracks_contains"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_tracks_contains.rs"
            

[[example]]
name = "current_user_saved_tracks_delete"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_tracks_delete.rs"
            

[[example]]
name = "current_user_saved_tracks"
required-features = ["blocking"]
path = "examples/blocking/current_user_saved_tracks.rs"
            

[[example]]
name = "current_user_top_artists"
required-features = ["blocking"]
path = "examples/blocking/current_user_top_artists.rs"
            

[[example]]
name = "current_user_top_tracks"
required-features = ["blocking"]
path = "examples/blocking/current_user_top_tracks.rs"
            

[[example]]
name = "featured_playlists"
required-features = ["blocking"]
path = "examples/blocking/featured_playlists.rs"
            

[[example]]
name = "me"
required-features = ["blocking"]
path = "examples/blocking/me.rs"
            

[[example]]
name = "new_releases"
required-features = ["blocking"]
path = "examples/blocking/new_releases.rs"
            

[[example]]
name = "next_playback"
required-features = ["blocking"]
path = "examples/blocking/next_playback.rs"
            

[[example]]
name = "pause_playback"
required-features = ["blocking"]
path = "examples/blocking/pause_playback.rs"
            

[[example]]
name = "playlist"
required-features = ["blocking"]
path = "examples/blocking/playlist.rs"
            

[[example]]
name = "previous_playback"
required-features = ["blocking"]
path = "examples/blocking/previous_playback.rs"
            

[[example]]
name = "recommendations"
required-features = ["blocking"]
path = "examples/blocking/recommendations.rs"
            

[[example]]
name = "repeat"
required-features = ["blocking"]
path = "examples/blocking/repeat.rs"
            

[[example]]
name = "blocking_search"
required-features = ["blocking"]
path = "examples/blocking/search.rs"
            

[[example]]
name = "seek_track"
required-features = ["blocking"]
path = "examples/blocking/seek_track.rs"
            

[[example]]
name = "shuffle"
required-features = ["blocking"]
path = "examples/blocking/shuffle.rs"
            

[[example]]
name = "start_playback"
required-features = ["blocking"]
path = "examples/blocking/start_playback.rs"
            

[[example]]
name = "transfer_playback"
required-features = ["blocking"]
path = "examples/blocking/transfer_playback.rs"
            

[[example]]
name = "user_artist_check_follow"
required-features = ["blocking"]
path = "examples/blocking/user_artist_check_follow.rs"
            

[[example]]
name = "user_follow_artists"
required-features = ["blocking"]
path = "examples/blocking/user_follow_artists.rs"
            

[[example]]
name = "user_follow_users"
required-features = ["blocking"]
path = "examples/blocking/user_follow_users.rs"
            

[[example]]
name = "user_playlist_add_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_add_tracks.rs"
            

[[example]]
name = "user_playlist_change_detail"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_change_detail.rs"
            

[[example]]
name = "user_playlist_check_follow"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_check_follow.rs"
            

[[example]]
name = "user_playlist_create"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_create.rs"
            

[[example]]
name = "user_playlist_follow_playlist"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_follow_playlist.rs"
            

[[example]]
name = "user_playlist_recorder_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_recorder_tracks.rs"
            

[[example]]
name = "user_playlist_remove_all_occurrences_of_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_remove_all_occurrences_of_tracks.rs"
            

[[example]]
name = "user_playlist_remove_specific_occurrenes_of_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_remove_specific_occurrenes_of_tracks.rs"
            

[[example]]
name = "user_playlist_replace_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_replace_tracks.rs"
            

[[example]]
name = "user_playlist"
required-features = ["blocking"]
path = "examples/blocking/user_playlist.rs"
            

[[example]]
name = "user_playlists"
required-features = ["blocking"]
path = "examples/blocking/user_playlists.rs"
            

[[example]]
name = "user_playlist_tracks"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_tracks.rs"
            

[[example]]
name = "user_playlist_unfollow"
required-features = ["blocking"]
path = "examples/blocking/user_playlist_unfollow.rs"
            

[[example]]
name = "user_unfollow_artists"
required-features = ["blocking"]
path = "examples/blocking/user_unfollow_artists.rs"
            

[[example]]
name = "user_unfollow_users"
required-features = ["blocking"]
path = "examples/blocking/user_unfollow_users.rs"
            

[[example]]
name = "volume"
required-features = ["blocking"]
path = "examples/blocking/volume.rs"

[[example]]
name = "blocking_get_access_token_without_cache"
required-features = ["blocking"]
path = "examples/blocking/get_access_token_without_cache.rs"

[[example]]
name = "blocking_save_shows"
required-features = ["blocking"]
path = "examples/blocking/save_shows.rs"

[[example]]
name = "blocking_get_saved_show"
required-features = ["blocking"]
path = "examples/blocking/get_saved_show.rs"

[[example]]
name = "blocking_get_a_show"
required-features = ["blocking"]
path = "examples/blocking/get_a_show.rs"

[[example]]
name = "blocking_get_several_shows"
required-features = ["blocking"]
path = "examples/blocking/get_several_shows.rs"

[[example]]
name = "blocking_get_shows_episodes"
required-features = ["blocking"]
path = "examples/blocking/get_shows_episodes.rs"

[[example]]
name = "blocking_get_an_episode"
required-features = ["blocking"]
path = "examples/blocking/get_an_episode.rs"

[[example]]
name = "blocking_get_several_episodes"
required-features = ["blocking"]
path = "examples/blocking/get_several_episodes.rs"

[[example]]
name = "blocking_check_users_saved_shows"
required-features = ["blocking"]
path = "examples/blocking/check_users_saved_shows.rs"

[[example]]
name = "blocking_remove_users_saved_shows"
required-features = ["blocking"]
path = "examples/blocking/remove_users_saved_shows.rs"